
module.exports = tagArray6 = [
  "vines",
  "science",
  "fruit",
  "putti",
  "collapsible",
  "garden design",
  "shapes",
  "angular",
  "system",
  "utility",
  "buildings",
  "theater",
  "engraving",
  "accountants",
  "thistles",
  "clams",
  "accordion",
  "movie poster",
  "art deco",
  "art nouveau",
  "bauhaus", 
  "bouquets",
  "cubism",
  "gradient",
  "mid-century modern",
  "modern",
  "modernism",
  "op art",
  "palm trees",
  "pattern",
  "postmodern",
  "sidewall", 
  "textile",
]